version: "3"
services:
  actual_server:
    container_name: actual_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${externalPort}:5006"
    volumes:
      - ${dataPath}:/data
    restart: unless-stopped
