version: "3"
services:
  actual_server:
    container_name: actual_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${externalPort}:5006"
    volumes:
      - ${serverFilesPath}:/app/server-files
      - ${userFilesPath}:/app/user-files
    restart: unless-stopped
